### PR TITLE
Update install-azurerm-ps.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Wow - that's critical information that's missing.

### CODE REVIEW

**Comment by sankethka** [comment]
@sdwheeler - Can you pls review this PR.

**Comment by sdwheeler** [comment]
The change submitted has totally wrecked the formatting. I cannot tell what the change was supposed to be. I am rejecting this PR.

@Rick-Anderson - what information is missing? Send me email with the details.

**Comment by Rick-Anderson** [comment]
@sdwheeler It's been so long I've forgotten. I think the new formatting is much better. I know there is some critical information missing in the original, can you look at the rendered doc?

**Comment by Rick-Anderson** [comment]
@sdwheeler  for some reason the formatting got messed up. If you run through the doc you'll see some needed information is missing.

**Comment by Rick-Anderson** [comment]
@sdwheeler  maybe this was the missing info
> [!NOTE]> If you have not previously set the PSGallery repository as a Trusted repository, you may see a prompt like the following:
 -		 +```Untrusted repositoryYou are installing the modules from an untrusted repository. If you trust this repository, change itsInstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from'PSGallery'?[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y```

**Comment by sdwheeler** [comment]
@Rick-Anderson that was it. I will get this added.

**Pull request closed without merging**
