### PR TITLE
Update Service Principal creation doc

### PR DESCRIPTION
**Pull request by maddieclayton**
Update service principal doc to reflect deprecation of the -Password parameter.

### CODE REVIEW

**Comment by sptramer** [comment]
@maddieclayton This seems to be a change for 6.13 only. Should it be merged Tuesday with the release?

**Comment by maddieclayton** [comment]
Oh I did not realize there were different versions of the doc - I just clicked edit on the page in docs.microsoft.com.  Can you point me to the correct place to edit?  The necessary changes are included in 6.13, so it should be available sometime after the Tuesday release.

**Comment by sptramer** [comment]
This is the correct version of the doc, but it shouldn't be published until 6.13 is publicly available. I'll merge it at that time.

**Comment by maddieclayton** [comment]
@sptramer Perfect thanks!

**Pull request merged**
