### PR TITLE
updating metadata for ref content

### PR DESCRIPTION
**Pull request by sdwheeler**
Updated docfx.json to use proper paths now that the processing repo is gone.

### CODE REVIEW

**Comment by sdwheeler** [comment]
@sankethka - please verify my changes

**Comment by sankethka** [comment]
@sdwheeler - This will not work. Need to use the moniker name instead of folder :-). What I have currently is after the processing repo is gone. so if you have to change any metadata pls only change value. Also, does this mean Carol is OK moving forward with an uber value 'azure-powershell'?

**Comment by sdwheeler** [comment]
@sankethka I reverted to the moniker names. Yes, Carol is OK with this change.

**Comment by sankethka** [comment]
@sdwheeler OK cool. I don't see it yet.... did u push? also no need to include anything for storage as its already in the correct moniker

**Comment by qinezh** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docfx.json](https://github.com/sdwheeler/azure-docs-powershell/blob/sdw-refmeta/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C26%5Cc57b8719-896e-5b94-9795-d62296555b61%5CPullRequest%5C201706261631105638-347%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sankethka** [comment]
@sdwheeler - I just noticed my latest fixes on metadata are not in master branch but instead on 'rd' branch. My bad.. I was experimenting why metadata was not showing up and we fixed this in rd brach but didn't push to master. You are working off master. Can u pls review this : https://github.com/Azure/azure-docs-powershell/blob/rd/docfx.json and submit your PR based on metadata format changes in this branch. Do submit to master. This way I won't merge mine to master and will delete my branch.

**Comment by sdwheeler** [comment]
@sankethka OK, I pulled the version from the rd branch and resubmitted my change.

**Comment by sankethka** [comment]
@sdwheeler all looks good except for row 356.. missing hyphen for azurestackps

**Comment by sdwheeler** [comment]
@sankethka Ok, fixed the missing hyphen - waiting for validation.

**Comment by qinezh** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docfx.json](https://github.com/sdwheeler/azure-docs-powershell/blob/sdw-refmeta/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C26%5Cc57b8719-896e-5b94-9795-d62296555b61%5CPullRequest%5C201706261814590406-347%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sankethka** [comment]
@sdwheeler All looks good now. will merge once validation is complete.

**Comment by qinezh** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docfx.json](https://github.com/sdwheeler/azure-docs-powershell/blob/sdw-refmeta/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C26%5Cc57b8719-896e-5b94-9795-d62296555b61%5CPullRequest%5C201706261854335989-347%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
#sign-off

**Pull request merged**
