### PR TITLE
Add odata filter example get azshealth

### PR DESCRIPTION
**Pull request by cblackuk**
When you have a lot of alerts it is much more efficient to use OData rather than getting all alerts and using very slow Where-Object to filter them.

Examples for OData are non-existent on Azure Stack so I created one.

Only the simple filter works for the moment sadly, but for alerts it is good enough.

### CODE REVIEW

**Comment by sptramer** [comment]
@cblackuk Please sign off and this will be merged.

**Comment by cblackuk** [comment]
signoff

**Comment by cblackuk** [comment]
@sign-off

**Comment by cblackuk** [comment]
#sign-off

**Pull request merged**
