### PR TITLE
Merging Sean's latest edits

### PR DESCRIPTION
**Pull request by TaraMeyer**

### CODE REVIEW

**Comment by sdwheeler** [comment]
@TaraMeyer - The update I made in PR#403 is not showing on the live site but it is in the live branch.

**Comment by TaraMeyer** [comment]
@sdwheeler - I'll do a manual build for you.

**Comment by TaraMeyer** [comment]
@sdwheeler - looks like we are good now, correct?

**Comment by sdwheeler** [comment]
@tarameyer - Yes, that did it. Thanks

**Pull request merged**
