### PR TITLE
Add Odata filter examples to get-azsippool

### PR DESCRIPTION
**Pull request by cblackuk**
Examples for OData are non-existent on Azure Stack so I created one.

It is much more efficient way of filtering than using Where-Object.

### CODE REVIEW

**Comment by sptramer** [comment]
@cblackuk Please sign off and this will be merged.

**Comment by cblackuk** [comment]
signoff

**Comment by cblackuk** [comment]
@sign-off

**Comment by cblackuk** [comment]
#sign-off

**Pull request merged**
