### PR TITLE
Update overview.md

### PR DESCRIPTION
**Pull request by maertendMSFT**
@sdwheeler & @twitchax, are you two ok with changes similar to this?  Trying to bring this up to speed with the equivalent CLI page.

### CODE REVIEW

**Comment by sdwheeler** [comment]
@maertendMSFT This does not belong in the overview. There are already examples like this in the Getting Started topic. Those examples are better candidates for the interactive experience. Work with @sptramer for those kind of content changes. He owns the AzurePS content now.

**Comment by twitchax** [comment]
@maertendMSFT, for my reference, which page in CLI docs were you trying to replicate?

**Comment by sptramer** [comment]
@maertendMSFT Please avoid this update for now. There is ongoing planning to change the CLI conceptual space to fit into the new MVC model, and part of that will be a rewrite of the landing/overview page.

**Comment by maertendMSFT** [comment]
We are looking to give more visibility to PowerShell in Cloud Shell and bring it up to par with the Bash equivalent.  

In order to do this, we want to link to Azure PowerShell from the Cloud Shell landing page (https://azure.microsoft.com/features/cloud-shell), a CLI link already exists.  In order for this link to be effective, we need a similar view to that of the Azure CLI page (https://docs.microsoft.com/cli/azure/index?view=azure-cli-latest), where we have an example that has the "Try It" button enabled and linking to the PowerShell experience in Cloud Shell in the first viewing window.

These changes accomplish this ask. 

@sptramer, I am assuming that with these changes a Azure PowerShell refactor is also coming, is that correct?

**Comment by sptramer** [comment]
Yes, eventually the Azure PowerShell documentation will be changed to align with the CLI, after we collect some data on performance.

**Pull request closed without merging**
