### PR TITLE
Restructure repo

### PR DESCRIPTION
**Pull request by qinezh**
@TaraMeyer  Here's the preview site for this branch: https://review.docs.microsoft.com/en-us/powershell/azure/overview?view=azurermps-4.4.1&branch=restucture

And the new folder structure of this repo: https://github.com/Azure/azure-docs-powershell/tree/restucture

One of the obvious benefit is that there's less warning message now.

Previous error message:  [see report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C30%5Cc57b8719-896e-5b94-9795-d62296555b61%5CCommit%5C201710302220528268-master%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=m6bDgl%2BkHShlPiMvUagrYRZZ2Pn9VSg%2Fpks0%2BXxTlYc%3D&st=2017-10-31T10%3A58%3A53Z&se=2017-12-01T11%3A03%3A53Z&sp=r)
Current error message: [see report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C31%5Cc57b8719-896e-5b94-9795-d62296555b61%5CCommit%5C201710311059393664-restucture%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XWFUB%2FUxDwGXWHFyLebI3dsU89MUXgKJ21W2tRzhuPs%3D&st=2017-10-31T12%3A51%3A30Z&se=2017-12-01T12%3A56%3A30Z&sp=r)

### CODE REVIEW

**Comment by qinezh** [comment]
No need to care about the PR validation status, as the branch already passed the build.

**Comment by TaraMeyer** [comment]
@qinezh - shall I merge now?  I have an Azure Stack release that I need to push on 11/1 (Tuesday) which means the repo will have a merge conflict and your work will have to be redone, which I would love to avoid this time :)

**Comment by TaraMeyer** [comment]
@qinezh  - looks like removing the standalone Azure.Storage and AzureRM.Storage folders is causing there to be two entries for Storage in the ToC.  I thought we needed to keep them in their own folders in order to avoid this?  https://review.docs.microsoft.com/en-us/powershell/azure/overview?view=azurermps-4.4.1&branch=restucture.

It also looks like we have multiple entries in the ToC for Virtual Machine, Service Bus, Storage, and Recovery Services:

image

**Comment by qinezh** [comment]
@TaraMeyer , the issue was due to the service group mapping breaks the rule: One service only exists in one module.

However, the service name `Storage` not only belongs to `AzureRM.Storage` but also `Azure.Storage`, which make the issue happened. So from my understanding, it should be content issue.

What I could do now is to merge items of same service into one node, which would be like the live branch. However, the root issue still exists.

**Comment by TaraMeyer** [comment]
@qinezh  what do you mean when you say it's a content issue?  There are two distinct modules - Azure.Storage and AzureRM.Storage.  When you say the root issue will still exist, what does that mean in terms of day-to-day?  Will we have errors in the builds?  Could the issue crop again.  It would help me to know that you can fix it to align to live now, but that we won't have issues crop up down the road because the set up breaks the rules.

**Comment by TaraMeyer** [comment]
@qinezh -per our discussion let's move forward with your updates.

**Comment by qinezh** [comment]
@TaraMeyer the issue mentioned above has been resolved, please see  https://review.docs.microsoft.com/en-us/powershell/azure/overview?view=azurermps-4.4.1&branch=restucture

**Pull request merged**
