### PR TITLE
47378

### PR DESCRIPTION
**Pull request by v-savila**
add note

### CODE REVIEW

**Comment by v-savila** [comment]
#sign-off from apexprod

**Comment by sptramer** [comment]
@v-savila - This updates old documentation only. If you need updates to the 5.x and 6.x documentation, please submit those separately. 6.x documentation must be updated as part of the main product, since reference for the current release is built in CI.

**Comment by v-savila** [comment]
@nitinme - Hi Nitin, please see comment above.

**Comment by cmcclister** [comment]
#sign-off apexprod cc @nitinme

**Comment by sptramer** [comment]
@v-savila @cmcclister Please do not sign off on this PR. Changes are required before it can be merged.

**Comment by v-savila** [comment]
@sptramer please see Nitin's comment above. 
cc @cmcclister

**Comment by sptramer** [comment]
This change isn't for the latest version. Please link me to a PR indicating that the latest version has been updated as well and I will merge.

**Comment by v-savila** [comment]
@sptramer do I just need to update 6.11 and can I use this same PR?

**Comment by sptramer** [comment]
@v-savila You need to update the PowerShell help directly, which will update the command-line help as well as our online ref. File a pull request aginst https://github.com/azure/azure-powershell, you can contact the engineering team (Mark Cowlishaw) for help.

**Comment by cmcclister** [comment]
@sptramer #hold-off please close this PR. We will reinstate this request once we have the necessary directions and guidance. Thank you, Christopher cc @v-savila @nitinme @markcowl

**Pull request closed without merging**
