### PR TITLE
fix formatting of note block

### PR DESCRIPTION
**Pull request by sdwheeler**

### CODE REVIEW

**Comment by sdwheeler** [comment]
#sign-off

**Comment by sankethka** [comment]
@sdwheeler Hey Sean - this one has no files? files changed shows as zero.. can u check pls?

**Comment by sdwheeler** [comment]
@sankethka As you can see, validation ran against overview.md. That is the file I changed. I removed one blank line that was breaking the format of a NOTE block.

**Comment by sdwheeler** [comment]
@sankethka I tweaked the formatting of the NOTE block again and resubmitted. Maybe GitHub will see the file as different now.

**Comment by sankethka** [comment]
OK I can see it now. will merge once validation is complete

**Pull request merged**
