### PR TITLE
Pushing restructuring of repo live

### PR DESCRIPTION
**Pull request by TaraMeyer**

### CODE REVIEW

**Comment by TaraMeyer** [comment]
@qinezh - I was able to successfully merge the restructuring commit to master, but I see now that they are conflicts that must be resolved in order to merge to live.  I'm not sure how there are conflicts, because the other commits listed in this pr - were already merged to live in previous days.  Are you able to help me resolve?  What should be my next steps?

**Comment by qinezh** [comment]
1: Never edit on live branch directly.
2: Always merge PR into master branch, and push master to live branch with git command in console.

Currently, you could push master to live branch with git command in console.

**Comment by qinezh** [comment]
@TaraMeyer

**Comment by qinezh** [comment]
The PR could be merged now after merging live branch in local and resolve the conflict.

**Pull request merged**
